import Head from 'next/head'
import Header from '../components/header'
import Welcome from '../components/welcome'
import About from '../components/about'
import Skills from '../components/skills'
import Projects from '../components/projects'
import Contact from '../components/contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Chirag | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <Header />
        <Welcome />
        <About />
        <Skills />
        <Projects />
        <Contact />
      </main>

      <footer></footer>
    </>
  )
}
